package:
  name: pyt3r_template
  version: 0.0.1

about:
  author : pyt3r
  license_file: LICENSE
  summary: a template package

source:
  path: ..

build:
  entry_points:
    - pyt3r_template-hello = template.scripts.hello:world

requirements:
  build:
    - python>= 3
    - pyyaml

  run:
    - python
